version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '01:33'
      timezone: Europe/Warsaw
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '01:44'
      timezone: Europe/Warsaw
    open-pull-requests-limit: 30
